<?php 
	if ( ! defined( 'ABSPATH' ) ) { 
		exit; // Exit if accessed directly
	}

 ?>
<?php 
	//if(isset( $_GET['action'] ) &&  $_GET['action'] == 'del_tax') {
	//	self::delete_tax();
	//}
 ?>
<div class="display_ez_tax_page">
	<h1>
		<?php esc_attr_e( 'Taxonomies', 'wp_admin_style' ); ?>
		<a class="button-primary add_new_button" href="<?php echo admin_url('admin.php?page=add-new-taxonomy'); ?>">Add New</a>
	</h1>
	
	<?php if (isset( $_GET['msg'] ) ) : ?>
		<?php if ($_GET['msg'] == 'del_tax') : ?>
			<div class="message updated">
				<p>Taxonomy Has Been Deleted</p>
			</div>
		<?php elseif ($_GET['msg'] == 'update_tax') : ?>
			<div class="message updated">
				<p>Taxonomy Has Been Updated</p>
			</div>
		<?php elseif ($_GET['msg'] == 'add_new') : ?>
			<div class="message updated">
				<p>Taxonomy Has Been Added</p>
			</div>
		<?php endif; ?>
	<?php endif; ?>
	
	<h2>Taxonomies Generated by EZ Custom Post Type Creator:</h2>
	
	<table class="widefat">
		<thead>
			<tr>
				<th class="row-title"><?php esc_attr_e( 'Taxonomy', 'wp_admin_style' ); ?></th>
				<th class="row-title"><?php esc_attr_e( 'Label', 'wp_admin_style' ); ?></th>
				<th class="row-title"><?php esc_attr_e( 'Attached Post Types', 'wp_admin_style' ); ?></th>
			</tr>
		</thead>
		<tbody>
		
			<?php 
				$current_tax = unserialize(get_option(CPT_TAX_OPTION_GROUP));
				$count = 0;
				if ($current_tax) :
					foreach($current_tax as $tax) :
					
						$del_url = admin_url( 'admin.php?page=taxonomies' ) . '&action=del_tax&key=' . $tax->unique_id;
						//$del_url = ( function_exists('wp_nonce_url') ) ? wp_nonce_url($del_url, 'nonce_del_tax') : $del_url;

				?>
						<tr class="<?php if ($count % 2 == 0) { echo 'alternate'; } ?>">
							<td class="row-title">
								<label for="tablecell">
									<?php esc_attr_e($tax->tax_name, 'wp_admin_style'); ?>
								</label><br>
								<div class="edit_wrap">
									<a href="<?php echo admin_url('admin.php?page=add-new-taxonomy&id='. $tax->unique_id); ?>">Edit</a><div class="line_break">|</div>
									<a href="<?php echo $del_url; ?>" title="<?php _e('Move this item to the Trash'); ?>"><?php _e('Delete', 'EZ_CPT_Creator'); ?></a>
									
									<!--<a href="<?php echo admin_url('admin.php?page=taxonomies&delete='. $tax->unique_id) ?>">Delete</a>-->
								</div>
								
							</td>
							<td>
								<?php esc_attr_e( $tax->menu_name, 'wp_admin_style' ); ?>
							</td>
							<td>
								<?php 
									if($tax->post_types) {
										foreach($tax->post_types as $posts) {
											esc_attr_e( $posts, 'wp_admin_style' );
											echo '<br>';
										}	
									}
								?>
							</td>
						</tr>
					<?php $count++; ?>
					<?php endforeach; ?>
				<?php endif; ?>
		</tbody>
		<tfoot>
			<tr>
				<th class="row-title"><?php esc_attr_e( 'Taxonomy', 'wp_admin_style' ); ?></th>
				<th class="row-title"><?php esc_attr_e( 'Label', 'wp_admin_style' ); ?></th>
				<th class="row-title"><?php esc_attr_e( 'Attached Post Types', 'wp_admin_style' ); ?></th>
			</tr>
		</tfoot>
	</table>
	<h2>Taxonomies Built Into WordPress:</h2>
	<table class="widefat">
		<thead>
			<tr>
				<th class="row-title"><?php esc_attr_e( 'Taxonomy', 'wp_admin_style' ); ?></th>
				<th class="row-title"><?php esc_attr_e( 'Label', 'wp_admin_style' ); ?></th>
				<th class="row-title"><?php esc_attr_e( 'Attached Post Types', 'wp_admin_style' ); ?></th>
			</tr>
		</thead>
		<tbody>

			<?php 
				$builtin_cpts = get_taxonomies( array(
					'_builtin' => true,
					), 'object'
				);
				$count = 0;
				if ($builtin_cpts) {
					foreach($builtin_cpts as $builtin) :
				?>
						<tr class="<?php if ($count % 2 == 0) { echo 'alternate'; } ?>">
							<td class="row-title">
								<label for="tablecell">
									<?php esc_attr_e($builtin->name, 'wp_admin_style'); ?>

								</label><br>
							</td>
							<td>
								<?php esc_attr_e( $builtin->label, 'wp_admin_style' ); ?>
							</td>
							<td>
								<?php
									foreach($builtin->object_type as $object) {
										esc_attr_e( $object, 'wp_admin_style' );
									} 
								?>
							</td>
						</tr>
					<?php $count++; ?>
					<?php endforeach; ?>
				<?php } ?>
		</tbody>
		<tfoot>
			<tr>
				<th class="row-title"><?php esc_attr_e( 'Taxonomy', 'wp_admin_style' ); ?></th>
				<th class="row-title"><?php esc_attr_e( 'Label', 'wp_admin_style' ); ?></th>
				<th class="row-title"><?php esc_attr_e( 'Attached Post Types', 'wp_admin_style' ); ?></th>
			</tr>
		</tfoot>
	</table>
</div>
